apiVersion: apps/v1
kind: Deployment
metadata:
  name: abalpha-kalotay-pricer
  labels:
    app: abalpha-kalotay-pricer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abalpha-kalotay-pricer
  template:
    metadata:
      labels:
        app: abalpha-kalotay-pricer
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: abalpha-kalotay-pricer
        image: acrfiquantitprod001.azurecr.io/abalpha-kalotay-pricer:latest
        resources:
          requests:
            cpu: "2000m"
            memory: "10Gi"
          limits:
            cpu: "2000m"
            memory: "10Gi"
        imagePullPolicy: "Always"
        volumeMounts:
        - name: fiquantit-mount
          # subPath: fiquantit-nfs
          mountPath: /fiquantit-nfs
        - name: fiquantit-jupyter-mount
          mountPath: /fiquantit-jupyter-nfs
        - name: fiquantit-modef-mount
          mountPath: /fiquantit-modef-nfs
        ports:
        - containerPort: 7878
        readinessProbe:
          httpGet:
            path: /heath/readiness
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 15
      tolerations:
      - key: "owner"
        operator: "Equal"
        value: "fiquant"
        effect: "NoSchedule"
      nodeSelector:
        owner: "fiquant"
      volumes:
      - name: fiquantit-mount
        persistentVolumeClaim:
          claimName: nfs-fiquantit-prod
      - name: fiquantit-jupyter-mount
        persistentVolumeClaim:
          claimName: nfs-fiquantit-jupyter
      - name: fiquantit-modef-mount
        persistentVolumeClaim:
          claimName: nfs-fiquantit-modef

---
kind: Service
apiVersion: v1
metadata:
  name: abalpha-kalotay-pricer
spec:
  type: LoadBalancer
  selector:
    app: abalpha-kalotay-pricer
  ports:
  - protocol: TCP
    name: http
    port: 7878
    targetPort: 7878
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: abalpha-kalotay-pricer
  namespace: fiquantit-prod
  labels:
    app: abalpha-kalotay-pricer
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "1000m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  tls:
  - hosts:
    - abalpha-kalotay-pricer.aks-fiquantit-prod-001.acml.com
  rules:
    - host: abalpha-kalotay-pricer.aks-fiquantit-prod-001.acml.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: abalpha-kalotay-pricer
                port:
                  name: http
